# Generated by Django 5.0.6 on 2024-05-20 10:37

import django.core.validators
import django.db.models.deletion
import userdata.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdatamodel',
            options={'verbose_name': 'Данные пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userprogramminglanguages',
            options={'verbose_name': 'Любимые языки программирования'},
        ),
        migrations.AddField(
            model_name='userdatamodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='biography',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='birth',
            field=models.DateField(validators=[userdata.validators.validate_date], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='fio',
            field=models.CharField(max_length=255, validators=[userdata.validators.validate_fio_format], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите 10-значный номер телефона', regex='^\\d{11}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='user_langs',
            field=models.ManyToManyField(to='userdata.userprogramminglanguages', verbose_name='Любимые языки программирования'),
        ),
        migrations.AlterField(
            model_name='userprogramminglanguages',
            name='programming_languages',
            field=models.CharField(max_length=255, verbose_name='Языки программирования'),
        ),
    ]
